# Generated by Django 5.2.3 on 2025-06-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customeraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
