# Generated by Django 5.2.3 on 2025-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
